name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§¾ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ³ Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: ğŸ”‘ Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ğŸ“¦ Build & Push User Service
        uses: docker/build-push-action@v4
        with:
          context: ./user_service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/user_service:latest

      - name: ğŸ“¦ Build & Push Shop Service
        uses: docker/build-push-action@v4
        with:
          context: ./shop_service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/shop_service:latest

      - name: ğŸ“¦ Build & Push Transaction Service
        uses: docker/build-push-action@v4
        with:
          context: ./transaction_service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/transaction_service:latest

      - name: ğŸ“¦ Build & Push API Gateway
        uses: docker/build-push-action@v4
        with:
          context: ./api_gateway
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/api_gateway:latest
